package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author khenj
 */
public class settings extends javax.swing.JFrame {
    
    public final Connection conn = new koneksi().konek();
    
    ImageIcon logo = new ImageIcon(getClass().getClassLoader().getResource("logo.png"));
    
    private void title(){
        String sql = "select * from app where id='1'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String name = hasil.getString("name");
                String version = hasil.getString("version");
                this.setTitle(name + " " + version);
            }
        } catch (Exception e) {
            this.setTitle("Warning : No Connection");
        }
    }
    
    public void dataApp(){
        String sql = "select * from app where id='1'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {                
                String id = hasil.getString("id");
                String name = hasil.getString("name");
                String version = hasil.getString("version");
                String appdesc = hasil.getString("description");
                labelAppId.setText(id);
                txtAppName.setText(name);
                txtVersion.setText(version);
                txtDescriptionApp.setText(appdesc);
            }
            title();
        } catch (Exception e) {
        }
    }
    
    public void dataComp(){
        String sql = "select * from company where comp_id='1'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {                
                String id = hasil.getString("comp_id");
                String name = hasil.getString("name");
                String address = hasil.getString("address");
                String description = hasil.getString("description");
                String trademark = hasil.getString("trademark");
                labelCompId.setText(id);
                txtCompName.setText(name);
                txtAddress.setText(address);
                txtDescriptionComp.setText(description);
                txtTrademark.setText(trademark);
            }
        } catch (Exception e) {
        }
    }
    
    public settings() {
        initComponents();
        title();
        dataApp();
        dataComp();
        this.setIconImage(logo.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelInventory = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        txtAppName = new javax.swing.JTextField();
        appVersion = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescriptionApp = new javax.swing.JTextArea();
        txtVersion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnChangeApp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelAppId = new javax.swing.JLabel();
        panelInventory1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        compName = new javax.swing.JLabel();
        txtCompName = new javax.swing.JTextField();
        compAddress = new javax.swing.JLabel();
        compDescription = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescriptionComp = new javax.swing.JTextArea();
        compTrademark = new javax.swing.JLabel();
        txtTrademark = new javax.swing.JTextField();
        compId = new javax.swing.JLabel();
        labelCompId = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnChangeComp = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panelInventory.setPreferredSize(new java.awt.Dimension(580, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 325));

        appName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        appName.setText("App Name");

        txtAppName.setPreferredSize(new java.awt.Dimension(170, 30));

        appVersion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        appVersion.setText("Version");
        appVersion.setPreferredSize(new java.awt.Dimension(64, 24));

        description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        description.setText("Description");

        txtDescriptionApp.setColumns(5);
        txtDescriptionApp.setLineWrap(true);
        txtDescriptionApp.setRows(4);
        txtDescriptionApp.setToolTipText("");
        txtDescriptionApp.setWrapStyleWord(true);
        txtDescriptionApp.setMinimumSize(new java.awt.Dimension(170, 30));
        jScrollPane2.setViewportView(txtDescriptionApp);

        txtVersion.setPreferredSize(new java.awt.Dimension(170, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appName)
                    .addComponent(description)
                    .addComponent(appVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAppName, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(txtVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAppName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnChangeApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/edit_24x24.png"))); // NOI18N
        btnChangeApp.setText("CHANGE");
        btnChangeApp.setToolTipText("Changes the information");
        btnChangeApp.setPreferredSize(new java.awt.Dimension(150, 30));
        btnChangeApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangeApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("App Id : ");

        labelAppId.setText("00");

        javax.swing.GroupLayout panelInventoryLayout = new javax.swing.GroupLayout(panelInventory);
        panelInventory.setLayout(panelInventoryLayout);
        panelInventoryLayout.setHorizontalGroup(
            panelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAppId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInventoryLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInventoryLayout.setVerticalGroup(
            panelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelAppId))
                .addGap(18, 18, 18)
                .addGroup(panelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("App", panelInventory);

        panelInventory1.setPreferredSize(new java.awt.Dimension(580, 600));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(375, 325));

        compName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compName.setText("Company Name");

        txtCompName.setPreferredSize(new java.awt.Dimension(170, 30));
        txtCompName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompNameActionPerformed(evt);
            }
        });

        compAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compAddress.setText("Address");

        compDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compDescription.setText("Description");

        txtAddress.setColumns(5);
        txtAddress.setLineWrap(true);
        txtAddress.setRows(4);
        txtAddress.setToolTipText("");
        txtAddress.setWrapStyleWord(true);
        txtAddress.setMinimumSize(new java.awt.Dimension(170, 30));
        jScrollPane3.setViewportView(txtAddress);

        txtDescriptionComp.setColumns(5);
        txtDescriptionComp.setLineWrap(true);
        txtDescriptionComp.setRows(4);
        txtDescriptionComp.setToolTipText("");
        txtDescriptionComp.setWrapStyleWord(true);
        txtDescriptionComp.setMinimumSize(new java.awt.Dimension(170, 30));
        jScrollPane4.setViewportView(txtDescriptionComp);

        compTrademark.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compTrademark.setText("Trademark");

        txtTrademark.setPreferredSize(new java.awt.Dimension(170, 30));
        txtTrademark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrademarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compName)
                    .addComponent(compAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compTrademark, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrademark, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(txtCompName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compAddress)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDescription)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrademark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compTrademark))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        compId.setText("Comp Id : ");

        labelCompId.setText("00");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnChangeComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/edit_24x24.png"))); // NOI18N
        btnChangeComp.setText("CHANGE");
        btnChangeComp.setToolTipText("Changes the information");
        btnChangeComp.setPreferredSize(new java.awt.Dimension(150, 30));
        btnChangeComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInventory1Layout = new javax.swing.GroupLayout(panelInventory1);
        panelInventory1.setLayout(panelInventory1Layout);
        panelInventory1Layout.setHorizontalGroup(
            panelInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventory1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventory1Layout.createSequentialGroup()
                        .addComponent(compId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCompId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInventory1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInventory1Layout.setVerticalGroup(
            panelInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventory1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compId)
                    .addComponent(labelCompId))
                .addGap(18, 18, 18)
                .addGroup(panelInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Company", panelInventory1);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("APP SETTINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(239, 239, 239)
                            .addComponent(title))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAppActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Do you want to change data", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            String sql = "update app set name=?, version=?, description=? where id = '1'";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, txtAppName.getText());
            stat.setString(2, txtVersion.getText());
            stat.setString(3, txtDescriptionApp.getText());
            stat.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Changed Succesfully");

            dataApp();
            txtAppName.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Invalid" + e);
        }
        }
        
    }//GEN-LAST:event_btnChangeAppActionPerformed

    private void txtCompNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompNameActionPerformed

    private void btnChangeCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeCompActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Do you want to change data", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            String sql = "update company set name=?, address=?, description=?, trademark=? where comp_id = '1'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);

                stat.setString(1, txtCompName.getText());
                stat.setString(2, txtAddress.getText());
                stat.setString(3, txtDescriptionComp.getText());
                stat.setString(4, txtTrademark.getText());
                stat.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Changed Succesfully");

                dataComp();
                txtCompName.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Invalid" + e);
            }
        }
        
    }//GEN-LAST:event_btnChangeCompActionPerformed

    private void txtTrademarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrademarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrademarkActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        title();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appName;
    private javax.swing.JLabel appVersion;
    private javax.swing.JButton btnChangeApp;
    private javax.swing.JButton btnChangeComp;
    private javax.swing.JLabel compAddress;
    private javax.swing.JLabel compDescription;
    private javax.swing.JLabel compId;
    private javax.swing.JLabel compName;
    private javax.swing.JLabel compTrademark;
    private javax.swing.JLabel description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAppId;
    private javax.swing.JLabel labelCompId;
    private javax.swing.JPanel panelInventory;
    private javax.swing.JPanel panelInventory1;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAppName;
    private javax.swing.JTextField txtCompName;
    private javax.swing.JTextArea txtDescriptionApp;
    private javax.swing.JTextArea txtDescriptionComp;
    private javax.swing.JTextField txtTrademark;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
